/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        bdg: {
          primary: '#4B5EFC',
          'primary-hover': '#6B7CFF',
          'primary-active': '#3344D1',
          secondary: '#1E97AD',
          surface: '#FFFFFF',
          'surface-variant': '#F8F9FA',
          'surface-elevated': '#FFFFFF',
          'on-surface': '#212529',
          'on-surface-variant': '#6C757D',
          'on-surface-muted': '#ADB5BD',
          outline: '#E9ECEF',
          'outline-variant': '#F1F3F5',
          'outline-strong': '#DEE2E6',
          success: '#059669',
          'success-container': '#ECFDF5',
          warning: '#D97706',
          'warning-container': '#FFFBEB',
          danger: '#DC2626',
          'danger-container': '#FEF2F2',
          info: '#4B5EFC',
          'info-container': '#EDF0FF',
        },
      },
      fontFamily: {
        inter: ['Inter'],
        'inter-medium': ['Inter-Medium'],
        'inter-semibold': ['Inter-SemiBold'],
        'inter-bold': ['Inter-Bold'],
      },
      spacing: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
      },
      borderRadius: {
        'bdg-sm': '4px',
        'bdg-md': '8px',
        'bdg-lg': '12px',
        'bdg-xl': '16px',
        'bdg-2xl': '20px',
      },
    },
  },
  plugins: [],
};
